[tool.poetry]
name = "actividad 1"
version = "0.1.0"
description = ""
authors = ["sebastiaanbv <jsballenvillalba@gmail.com>"]
license = "\"MIT\""

[tool.poetry.dependencies]
python = "3.10"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
